# appspec.yml for EC2 deployment in CodeDeploy.
version: 0.0
os: linux
files:
  - source: /
    destination: /digitaltwin
hooks:
  BeforeInstall:
    - location: aws_scripts/install_nodejs.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws_scripts/install_npm_packages.sh
      timeout: 300
      runas: root
    - location: aws_scripts/npm_build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_server.sh
      timeout: 60
      runas: root
